linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
matrix:
   include:

      - <<: *linux
        env: CONAN_GCC_VERSIONS=6.3 CONAN_DOCKER_IMAGE=conanio/gcc63

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
